Boake-BackEnd/Models/About.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;

namespace Boake_BackEnd.Models
{
    public class About :BaseEntity
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }
    }
}

Boake-BackEnd/Areas/AdminArea/Controllers/AboutController.cs
using Boake_BackEnd.DAL;
using Boake_BackEnd.Helpers;
using Boake_BackEnd.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Boake_BackEnd.Extensions;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace Boake_BackEnd.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize(Roles = "SuperAdmin")]

    public class AboutController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public AboutController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public IActionResult Index()
        {
            About blogs = _context.Abouts.Where(b => !b.IsDeleted).FirstOrDefault();
            return View(blogs);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            About db = _context.Abouts.Find(id);
            if (db == null) return NotFound();
            db.IsDeleted = true;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(About about)
        {
            if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
            {
                return View();
            }

            if (!about.Photo.IsImage())
            {
                ModelState.AddModelError("Photo", "Sekil Formati secin");
            }

            if (about.Photo.CheckSize(20000))
            {
                ModelState.AddModelError("Photo", "Sekil 20 mb-dan boyuk ola bilmez");
            }

            string filename = await about.Photo.SaveFile(_env, "assets/img/about");
            about.ImageUrl = filename;

            about.CreatedTime = DateTime.Now;
             
            _context.Abouts.Add(about);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
             
            About about = _context.Abouts.Find(id);
            if (about == null)
            {
                return NotFound();
            }
            return View(about);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int? id, About about)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.Tags = _context.Tags.Where(t => !t.IsDeleted).ToList();

           
            About db = _context.Abouts.Find(id);
            if (db == null)
            {
                return NotFound();
            }
            if (about.Photo != null)
            {

                if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                {
                    return View();
                }

                if (!about.Photo.IsImage())
                {
                    ModelState.AddModelError("Photo", "Sekil Formati secin");
                }

                if (about.Photo.CheckSize(20000))
                {
                    ModelState.AddModelError("Photo", "Sekil 20 mb-dan boyuk ola bilmez");
                }
                Helper.DeleteFile(_env, "assets/img/about", db.ImageUrl);
                string filename = await about.Photo.SaveFile(_env, "assets/img/about");
                db.ImageUrl = filename;
            }
            else
            {
                db.ImageUrl = db.ImageUrl;
            } 
            About existName = _context.Abouts.FirstOrDefault(x => x.Name.ToLower() == about.Name.ToLower());

            if (existName != null)
            {
                if (db != existName)
                {
                    ModelState.AddModelError("Name", "Name Already Exist");
                    return View();
                }
            }
             
            db.Name = about.Name;
            db.Description = about.Description;
            db.UpdatedTime = DateTime.Now;
            

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Boake-BackEnd/Controllers/AboutController.cs
using Boake_BackEnd.DAL;
using Boake_BackEnd.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Boake_BackEnd.Controllers
{
    public class AboutController : Controller
    {
        private readonly AppDbContext _context;

        public AboutController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            About about = _context.Abouts.FirstOrDefault(a=>!a.IsDeleted);
            return View(about);
        }
    }
}

Boake-BackEnd/Areas/AdminArea/Views/About/Create.cshtml
@model About
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml"; 
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">

                <form method="post" enctype="multipart/form-data">

                    <div class="mb-3">
                        <label asp-for="Photo" class="form-label">Photo</label>
                        <input asp-for="Photo" accept="image/*" class="form-control">
                        <span asp-validation-for="@Model.Photo" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Name" class="form-label">Name</label>
                        <input asp-for="Name" class="form-control">
                        <span asp-validation-for="@Model.Name" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Description" class="form-label">Description</label>
                        <input asp-for="Description" class="form-control">
                        <span asp-validation-for="@Model.Description" class="text-danger"></span>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

Boake-BackEnd/Areas/AdminArea/Views/About/Edit.cshtml
@model About
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">

                <form method="post" enctype="multipart/form-data">

                    <div class="mb-3">
                        <label asp-for="Photo" class="form-label">Photo</label>
                        <input asp-for="Photo" accept="image/*" class="form-control">
                        <span asp-validation-for="@Model.Photo" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Name" class="form-label">Name</label>
                        <input asp-for="Name" class="form-control">
                        <span asp-validation-for="@Model.Name" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Description" class="form-label">Description</label>
                        <input asp-for="Description" class="form-control">
                        <span asp-validation-for="@Model.Description" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

Boake-BackEnd/Areas/AdminArea/Views/About/Index.cshtml
@model About
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}
@if (Model!=null)
{
    
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Basic Table</h6>
                <a asp-area="AdminArea" asp-controller="About" asp-action="Create" class="btn btn-success">Create</a>
                <table class="table">
                    <thead>
                        <tr>

                            <th scope="col">Image</th>
                            <th scope="col">Name</th>
                            <th scope="col">Description</th>
                            <th scope="col">Delete</th>
                            <th scope="col">Detail</th> 

                        </tr>
                    </thead>
                    <tbody>

                        <tr>

                            <td><img style="width:100px;" src="~/assets/img/about/@Model.ImageUrl" /></td>
                            <td>@Model.Name</td>

                            <td>@Model.Description</td>
                            <td><a asp-area="adminarea" asp-controller="About" asp-action="delete" asp-route-id="@Model.Id" class="btn btn-danger  ">Delete</a></td>
                            <td><a asp-area="adminarea" asp-controller="About" asp-action="edit" asp-route-id="@Model.Id" class="btn btn-warning  ">Edit</a></td> 

                        </tr>


                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
}