Boake-BackEnd/Areas/AdminArea/Controllers/TypeController.cs
using Boake_BackEnd.DAL;
using Boake_BackEnd.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Boake_BackEnd.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    [Authorize(Roles = "SuperAdmin")]

    public class TypeController : Controller
    {
        private readonly AppDbContext _context;

        public TypeController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<ProductType> productTypes = await _context.ProductTypes.Where(m => !m.IsDeleted).AsNoTracking().OrderByDescending(m => m.Id).ToListAsync();
            return View(productTypes);

        }

        //[Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductType productType)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }


                bool isExist = await _context.ProductTypes.AnyAsync(m => m.Name.Trim() == productType.Name.Trim());

                if (isExist)
                {
                    ModelState.AddModelError("Name", "Product Type already exist");
                    return View();
                }


                await _context.ProductTypes.AddAsync(productType);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }

        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            ProductType productType = await _context.ProductTypes.FirstOrDefaultAsync(m => m.Id == id);

            productType.IsDeleted = true;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id is null) return BadRequest();

                ProductType productType = await _context.ProductTypes.FirstOrDefaultAsync(m => m.Id == id);

                if (productType is null) return NotFound();

                return View(productType);

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductType productType)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(productType);
                }

                ProductType dbProductType = await _context.ProductTypes.AsNoTracking().FirstOrDefaultAsync(m => m.Id == id);

                if (dbProductType is null) return NotFound();

                if (dbProductType.Name.ToLower().Trim() == productType.Name.ToLower().Trim())
                {
                    return RedirectToAction(nameof(Index));
                }

                dbProductType.Name = productType.Name;

                _context.ProductTypes.Update(productType);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {

                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

Boake-BackEnd/Areas/AdminArea/Views/Type/Create.cshtml
@model ProductType

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">

                <form method="post" enctype="multipart/form-data">

                    <div class="mb-3">
                        <label asp-for="Name" class="form-label">Name</label>
                        <input asp-for="Name" class="form-control">
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

Boake-BackEnd/Areas/AdminArea/Views/Type/Edit.cshtml
@model ProductType

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">

                <form method="post" enctype="multipart/form-data">

                    <div class="mb-3">
                        <label asp-for="Name" class="form-label">Name</label>
                        <input asp-for="Name" class="form-control">
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

Boake-BackEnd/Areas/AdminArea/Views/Type/Index.cshtml
@model List<ProductType>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
    int counter = 0;
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-secondary rounded h-100 p-4">
                <h6 class="mb-4">Basic Table</h6>
                <a asp-area="AdminArea" asp-controller="Type" asp-action="Create" class="btn btn-success">Create</a>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">ProductType Name</th>
                            <th scope="col">Delete</th>
                            <th scope="col">Update</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            counter++;
                            <tr>
                                <th scope="row">@counter</th>
                                <td>@item.Name</td>
                                <td><a asp-area="adminarea" asp-controller="Type" asp-action="delete" asp-route-id="@item.Id" class="btn btn-danger  ">Delete</a></td>
                                <td><a asp-area="adminarea" asp-controller="Type" asp-action="edit" asp-route-id="@item.Id" class="btn btn-warning  ">Edit</a></td>

                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>